### ISSUE TITLE
[Bug] Game crashes or freezes when setting values to low or negative numbers.

### ISSUE THREAD

**Issue by Magg27** [Fruitloopins/Tabby#1]
## Bug

When values below 0 are present in the `text.autoconfig.Tabby.option.maxCount` & `text.autoconfig.Tabby.option.adaptiveDivisor` field, the game will crash. When values below 1 are present in the `text.autoconfig.Tabby.option.maxRows` field, the game will either freeze or crash.

## Solution

Don't allow for values lower than what is possible without a crash in the config menu.

**Comment by jwkerr** [comment]
i could definitely do that but i kept it like that since i thought people might be curious to see what it does, in my experience it just lagged a bit but if it causes crashes i will put limits on it

**Comment by jwkerr** [comment]
yeah i just checked and it does crash, i will patch it later

**Comment by jwkerr** [comment]
should be patched in [v1.3.2](https://github.com/Fruitloopins/Tabby/releases/tag/v1.3.2) @Magg27
