### ISSUE TITLE
Add translation strings for config tooltips

### ISSUE THREAD

**Issue by fungoza** [Fruitloopins/Tabby#9]
Make config tooltips translatable

**Comment by jwkerr** [comment]
if you can make a pull request for another language i can add it

**Comment by fungoza** [comment]
> if you can make a pull request for another language i can add it

en_us.json doesn't have localization keys for tooltips

**Comment by GalaxyGaming2000** [comment]
> > if you can make a pull request for another language i can add it
> 
> en_us.json doesn't have localization keys for tooltips

What do you mean?

**Comment by fungoza** [comment]
> > > if you can make a pull request for another language i can add it
> > 
> > 
> > en_us.json doesn't have localization keys for tooltips
> 
> What do you mean?

look this
https://github.com/Fruitloopins/Tabby/blob/master/src/main/resources/assets/tabby/lang/en_us.json
and this
https://github.com/Fruitloopins/Tabby/blob/master/src/main/java/com/fwloopins/tabby/config/TabbyConfig.java
no translate keys for `@Comment` sections (looks like tooltips in minecraft)

**Comment by jwkerr** [comment]
i'll have a look at adding it tomorrow

**Comment by jwkerr** [comment]
@FurnyGo i've added config tooltip translation strings
